// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DFScenarioScopeEntry struct {
	DaDimLevelColumnName string `json:"daDimLevelColumnName"`
	DaDimMemberID        string `json:"daDimMemberId"`
}

type DFScenarioScopeEntryInput struct {
	DaDimLevelColumnName string `json:"daDimLevelColumnName"`
	DaDimMemberID        string `json:"daDimMemberId"`
}

type Tag struct {
	TagID   int     `json:"tagId"`
	TagName *string `json:"tagName"`
}

func (Tag) IsEntity() {}

type User struct {
	UserID    string  `json:"userId"`
	FirstName *string `json:"firstName"`
}

func (User) IsEntity() {}
